# GitHub Actions - CI for Go to build & test.
# https://github.com/fxamacker/cbor/workflows/ci.yml
# See ci-go-cover.yml for coverage and safer-golangci-lint.yml for linting.
name: ci

# Revoke default permissions.
permissions: {}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
      - 'release*'
      - 'feature/stream-mode'
    tags:
      - 'v*'  
jobs:
  # Test on various OS with default Go version. 
  tests:
    name: test ${{matrix.os}} go-${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go-version: [1.17, 1.18, 1.19, '1.20', 1.21, 1.22, 1.23]
    steps:
    - name: Install Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 1

    - name: Print Go version
      run: go version

    - name: Get dependencies
      run: go get -v -t -d ./...
      
    - name: Build project
      run: go build ./...
      
    - name: Run tests
      run: |
        go version
        go test -race -v ./...
